#!/bin/sh

if [ $# -ne 1 ] ; then
    echo "One argument is needed" 1>&2;
    exit 1;
fi

if [ ! -d $1 ] ; then
    echo "Argument is not a directory" 1>&2;
    exit 2;
fi

git submodule deinit -f $1

git rm -f $1

rm -rf .git/modules/$1

rm -rf $1

echo "Submodule Removed Successfully"

echo "Add, Commit and Push to remove the $1 submodule from the remote"
